### ISSUE TITLE
How does this show results

### ISSUE THREAD

**Issue by zarishhk** [zihenlin/DySTUrbD-Pytorch#1]
Hi, this isn't really an issue but just a question as to how the results of the simulation can be seen, is there a webapp that shows the result?

**Comment by zihenlin** [comment]
Hi, currently we put the emphasis on debugging and optimizing the model, therefore we do not have a nice automated mechanism for visualization yet.

The simulation produces an output json file. You could obtain and plot the your desired output from there. A good starting point is [this script](https://github.com/amirca91/DySTUrbD/blob/COVID_ABM/create_figures.py) from the original repository. 

Please kindly note that you could also run the model from [this repo](https://github.com/yair-grinb/Covid-lockdown-sim), which was specifically setup for running on personal computer with dummy data. This pytorch version is designed to deal with big data.
